version: '3.8'

services:
  hypervector-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: development
    container_name: hypervector-api
    ports:
      - "8000:8000"
    environment:
      - HYPERVECTOR_ENV=development
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - hypervector-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  prometheus:
    image: prom/prometheus:latest
    container_name: hypervector-prometheus
    ports:
      - "9090:9090"
    networks:
      - hypervector-network
    restart: unless-stopped

networks:
  hypervector-network:
    driver: bridge
