# Monitoring configuration for HyperVector-Lab
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'hypervector-api'
        static_configs:
          - targets: ['hypervector-api:8000']
        metrics_path: '/metrics'
        scrape_interval: 15s
        scrape_timeout: 10s
