apiVersion: v1
kind: Service
metadata:
  labels:
    app: hypervector-app
  name: hypervector-app-service
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hypervector-app
  type: LoadBalancer
