apiVersion: v1
kind: Service
metadata:
  name: hypervector-api
  labels:
    app: hypervector
    component: api
    environment: production
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: hypervector
    component: api
