version: '3.8'

services:
  hypervector-app:
    build: .
    container_name: hypervector-lab
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - HDC_LOG_LEVEL=INFO
      - HDC_CACHE_SIZE=512
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import hypervector; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'

  hypervector-worker:
    build: .
    container_name: hypervector-worker
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - HDC_WORKER_MODE=true
    volumes:
      - ./data:/app/data
    depends_on:
      - hypervector-app
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

  monitoring:
    image: prom/prometheus:latest
    container_name: hypervector-monitoring
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

volumes:
  data:
  logs:
  prometheus_data:

networks:
  default:
    name: hypervector-network
